"""
Common type definitions, protocols.
"""

from typing import (
    Any,
    Dict,
    Optional,
    Protocol,
    Tuple,
    Union,
    TypeVar,
    Sequence,
    Mapping,
    runtime_checkable,
    Self,
    TypeAlias,
    TypedDict,
)


Params: TypeAlias = Union[Sequence[Any], Mapping[str, Any]]
Row: TypeAlias = Union[Tuple[Any, ...], Dict[str, Any]]
SQL: TypeAlias = str


T = TypeVar("T", covariant=True)
T_contra = TypeVar("T_contra", contravariant=True)


@runtime_checkable
class AsyncCursor(Protocol[T]):
    """Protocol for DB-API 2.0 async cursor objects"""

    async def execute(self, sql: SQL, parameters: Optional[Params] = ...) -> Any: ...
    async def executemany(
        self, sql: SQL, seq_of_parameters: Sequence[Params]
    ) -> Any: ...
    async def fetchone(self) -> Optional[T]: ...
    async def fetchmany(self, size: int = ...) -> Sequence[T]: ...
    async def fetchall(self) -> Sequence[T]: ...
    @property
    def description(self) -> Optional[Sequence[Tuple[str, ...]]]: ...
    @property
    def rowcount(self) -> int: ...
    async def close(self) -> Any: ...
    async def setinputsizes(self, sizes: Sequence[Any]) -> None: ...
    async def setoutputsize(self, size: int, column: Optional[int] = ...) -> None: ...
    def __aiter__(self) -> Self: ...
    async def __anext__(self) -> Row: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...


@runtime_checkable
class AsyncConnection(Protocol):
    """Protocol for DB-API 2.0 async connection objects"""

    async def cursor(self) -> AsyncCursor: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def close(self) -> None: ...
    @property
    def autocommit(self) -> bool: ...
    @autocommit.setter
    def autocommit(self, value: bool) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...


@runtime_checkable
class Cursor(Protocol[T]):
    """Protocol for DB-API 2.0 cursor objects"""

    def execute(self, sql: SQL, parameters: Optional[Params] = ...) -> Any: ...
    def executemany(self, sql: SQL, seq_of_parameters: Sequence[Params]) -> Any: ...
    def fetchone(self) -> Optional[T]: ...
    def fetchmany(self, size: int = ...) -> Sequence[T]: ...
    def fetchall(self) -> Sequence[T]: ...
    @property
    def description(self) -> Optional[Sequence[Tuple[str, ...]]]: ...
    @property
    def rowcount(self) -> int: ...
    def close(self) -> Any: ...
    def setinputsizes(self, sizes: Sequence[Any]) -> None: ...
    def setoutputsize(self, size: int, column: Optional[int] = ...) -> None: ...
    def __iter__(self) -> Row: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...


@runtime_checkable
class Connection(Protocol):
    """Protocol for DB-API 2.0 connection objects"""

    def cursor(self) -> Cursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    @property
    def autocommit(self) -> bool: ...
    @autocommit.setter
    def autocommit(self, value: bool) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...


class ConnectionConfig(TypedDict, total=False):
    """Typed dict for connection parameters"""

    host: str
    port: int
    dialect: str
    driver: str
    database: str
    user: str
    password: str
    autocommit: bool
    extras: Dict[str, Any]


class PoolConfig(TypedDict, total=False):
    """Typed dict for pool configuration"""

    min_size: int
    max_size: int
    max_queries: int
    max_inactive_seconds: int
    timeout_seconds: float
